//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFServiceApp.DatabaseEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationMst
    {
        public int RelationId { get; set; }
        public string RelationName { get; set; }
    }
}
