//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyRecodSystem.ServiceRef_LoginRegistration {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDetail", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceApp.DatabaseEntity")]
    [System.SerializableAttribute()]
    public partial class UserDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef_LoginRegistration.ILoginRegistrationService")]
    public interface ILoginRegistrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginRegistrationService/DoWork", ReplyAction="http://tempuri.org/ILoginRegistrationService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginRegistrationService/DoWork", ReplyAction="http://tempuri.org/ILoginRegistrationService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginRegistrationService/CheckLogin", ReplyAction="http://tempuri.org/ILoginRegistrationService/CheckLoginResponse")]
        FamilyRecodSystem.ServiceRef_LoginRegistration.UserDetail CheckLogin(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginRegistrationService/CheckLogin", ReplyAction="http://tempuri.org/ILoginRegistrationService/CheckLoginResponse")]
        System.Threading.Tasks.Task<FamilyRecodSystem.ServiceRef_LoginRegistration.UserDetail> CheckLoginAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginRegistrationService/Register", ReplyAction="http://tempuri.org/ILoginRegistrationService/RegisterResponse")]
        int Register(string userName, string email, string password, string userType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginRegistrationService/Register", ReplyAction="http://tempuri.org/ILoginRegistrationService/RegisterResponse")]
        System.Threading.Tasks.Task<int> RegisterAsync(string userName, string email, string password, string userType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginRegistrationServiceChannel : FamilyRecodSystem.ServiceRef_LoginRegistration.ILoginRegistrationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginRegistrationServiceClient : System.ServiceModel.ClientBase<FamilyRecodSystem.ServiceRef_LoginRegistration.ILoginRegistrationService>, FamilyRecodSystem.ServiceRef_LoginRegistration.ILoginRegistrationService {
        
        public LoginRegistrationServiceClient() {
        }
        
        public LoginRegistrationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginRegistrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginRegistrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginRegistrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public FamilyRecodSystem.ServiceRef_LoginRegistration.UserDetail CheckLogin(string userName, string password) {
            return base.Channel.CheckLogin(userName, password);
        }
        
        public System.Threading.Tasks.Task<FamilyRecodSystem.ServiceRef_LoginRegistration.UserDetail> CheckLoginAsync(string userName, string password) {
            return base.Channel.CheckLoginAsync(userName, password);
        }
        
        public int Register(string userName, string email, string password, string userType) {
            return base.Channel.Register(userName, email, password, userType);
        }
        
        public System.Threading.Tasks.Task<int> RegisterAsync(string userName, string email, string password, string userType) {
            return base.Channel.RegisterAsync(userName, email, password, userType);
        }
    }
}
